name: app_shield
description: >
  App Shield: A robust Flutter plugin for app security, featuring screenshot prevention, SSL pinning, app integrity checks, and print management for safe production.
homepage: https://github.com/Xazin/app_shield
repository: https://github.com/Xazin/app_shield
version: 0.0.3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"  

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface:
  dio:
  freerasp: ^8.2.2
  fluttertoast:
  screen_protector:

dependency_overrides:
  meta:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  plugin:
    platforms:
      android:
        package: dev.app_shield.app_shield
        pluginClass: AppShieldPlugin
      ios:
        pluginClass: AppShieldPlugin